### ISSUE TITLE
Akan loglar nasıl durur?

### ISSUE THREAD

**Issue by geocmsk** [ruesandora/Elixir#2]
mobaxterm ile erişim sağlıyorum ancak ctrl+c ile durmuyor. Nasıl durdurabilirim hocam?

**Comment by ruesandora** [comment]
hangi node?

**Comment by geocmsk** [comment]
elixir hocam

**Comment by ruesandora** [comment]
ctrl c hocam

**Comment by geocmsk** [comment]
> ctrl c hocam

malesef çok denedim durmuyor hocam işlemiyor ctrl+c

^C şeklinde görüntülüyor

**Comment by geocmsk** [comment]
> ctrl c hocam

hocam kill -9 PID ile durdurdum sonunda konuyu kapatabiliriz teşekkürler

**Comment by Madmin27** [comment]
kill -9 PID ile durdurursan node'u da durdurmş olursun
Ctrl + D ile durdrursan da öyle

Ctrl +A ve ctrl'den elini kaldırmadan D bas
Yani Ctrl A +D

**Comment by geocmsk** [comment]
> kill -9 PID ile durdurursan node'u da durdurmş olursun Ctrl + D ile durdrursan da öyle
> 
> Ctrl +A ve ctrl'den elini kaldırmadan D bas Yani Ctrl A +D

amacım screenden çıkmak değil, durdurmak zaten teşekkürler
